//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.Sunat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.sunat.gob.pe", ConfigurationName="Sunat.billValidService")]
    public interface billValidService {
        
        // CODEGEN: El parámetro 'cdpvalidado' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:validaCDPcriterios", ReplyAction="http://service.sunat.gob.pe/billValidService/validaCDPcriteriosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cdpvalidado")]
        Tools.Sunat.validaCDPcriteriosResponse validaCDPcriterios(Tools.Sunat.validaCDPcriteriosRequest request);
        
        // CODEGEN: El parámetro 'archivoverificado' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:verificaCPEarchivo", ReplyAction="http://service.sunat.gob.pe/billValidService/verificaCPEarchivoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="archivoverificado")]
        Tools.Sunat.verificaCPEarchivoResponse verificaCPEarchivo(Tools.Sunat.verificaCPEarchivoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sunat.gob.pe")]
    public partial class statusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] contentField;
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("statusMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaCDPcriterios", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class validaCDPcriteriosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rucEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoCDP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serieCDP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroCDP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDocIdReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocIdReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaEmision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double importeTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nroAutorizacion;
        
        public validaCDPcriteriosRequest() {
        }
        
        public validaCDPcriteriosRequest(string rucEmisor, string tipoCDP, string serieCDP, string numeroCDP, string tipoDocIdReceptor, string numeroDocIdReceptor, string fechaEmision, double importeTotal, string nroAutorizacion) {
            this.rucEmisor = rucEmisor;
            this.tipoCDP = tipoCDP;
            this.serieCDP = serieCDP;
            this.numeroCDP = numeroCDP;
            this.tipoDocIdReceptor = tipoDocIdReceptor;
            this.numeroDocIdReceptor = numeroDocIdReceptor;
            this.fechaEmision = fechaEmision;
            this.importeTotal = importeTotal;
            this.nroAutorizacion = nroAutorizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaCDPcriteriosResponse", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class validaCDPcriteriosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Tools.Sunat.statusResponse cdpvalidado;
        
        public validaCDPcriteriosResponse() {
        }
        
        public validaCDPcriteriosResponse(Tools.Sunat.statusResponse cdpvalidado) {
            this.cdpvalidado = cdpvalidado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificaCPEarchivo", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class verificaCPEarchivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string archivo;
        
        public verificaCPEarchivoRequest() {
        }
        
        public verificaCPEarchivoRequest(string nombre, string archivo) {
            this.nombre = nombre;
            this.archivo = archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificaCPEarchivoResponse", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class verificaCPEarchivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Tools.Sunat.statusResponse archivoverificado;
        
        public verificaCPEarchivoResponse() {
        }
        
        public verificaCPEarchivoResponse(Tools.Sunat.statusResponse archivoverificado) {
            this.archivoverificado = archivoverificado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface billValidServiceChannel : Tools.Sunat.billValidService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class billValidServiceClient : System.ServiceModel.ClientBase<Tools.Sunat.billValidService>, Tools.Sunat.billValidService {
        
        public billValidServiceClient() {
        }
        
        public billValidServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public billValidServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public billValidServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public billValidServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tools.Sunat.validaCDPcriteriosResponse Tools.Sunat.billValidService.validaCDPcriterios(Tools.Sunat.validaCDPcriteriosRequest request) {
            return base.Channel.validaCDPcriterios(request);
        }
        
        public Tools.Sunat.statusResponse validaCDPcriterios(string rucEmisor, string tipoCDP, string serieCDP, string numeroCDP, string tipoDocIdReceptor, string numeroDocIdReceptor, string fechaEmision, double importeTotal, string nroAutorizacion) {
            Tools.Sunat.validaCDPcriteriosRequest inValue = new Tools.Sunat.validaCDPcriteriosRequest();
            inValue.rucEmisor = rucEmisor;
            inValue.tipoCDP = tipoCDP;
            inValue.serieCDP = serieCDP;
            inValue.numeroCDP = numeroCDP;
            inValue.tipoDocIdReceptor = tipoDocIdReceptor;
            inValue.numeroDocIdReceptor = numeroDocIdReceptor;
            inValue.fechaEmision = fechaEmision;
            inValue.importeTotal = importeTotal;
            inValue.nroAutorizacion = nroAutorizacion;
            Tools.Sunat.validaCDPcriteriosResponse retVal = ((Tools.Sunat.billValidService)(this)).validaCDPcriterios(inValue);
            return retVal.cdpvalidado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tools.Sunat.verificaCPEarchivoResponse Tools.Sunat.billValidService.verificaCPEarchivo(Tools.Sunat.verificaCPEarchivoRequest request) {
            return base.Channel.verificaCPEarchivo(request);
        }
        
        public Tools.Sunat.statusResponse verificaCPEarchivo(string nombre, string archivo) {
            Tools.Sunat.verificaCPEarchivoRequest inValue = new Tools.Sunat.verificaCPEarchivoRequest();
            inValue.nombre = nombre;
            inValue.archivo = archivo;
            Tools.Sunat.verificaCPEarchivoResponse retVal = ((Tools.Sunat.billValidService)(this)).verificaCPEarchivo(inValue);
            return retVal.archivoverificado;
        }
    }
}
